pipelines:
  default:
    - step: &build_step
        name: Build
        image: mcr.microsoft.com/dotnet/sdk:6.0
        caches:
          - dotnetcore
        script:
          - dotnet publish -c Release
          - cp -ar ReportGenerator/bin/*/*/publish publish
        artifacts:
          - publish/**
  pull-requests:
    '**':
      - step: *build_step
  branches:
    master:
      - step:
          name: Build and upload
          image: mcr.microsoft.com/dotnet/sdk:6.0
          caches:
            - dotnetcore
            - docker
          script:
            - dotnet publish -c Release
            - cp -ar ReportGenerator/bin/*/*/publish publish
            - docker login -u "$DOCKER_HUB_USER" -p "$DOCKER_HUB_PASSWORD"
            # Workaround for pipes not supporting private docker repos.
            - docker pull myprocessx/upload-artifact
            - pipe: ozma-io/upload-artifact:master
              variables:
                LOCAL_PATH: publish
          artifacts:
            - artifact.json
      - step:
          name: Deploy to test
          deployment: test
          caches:
            - docker
          script:
            - docker login -u "$DOCKER_HUB_USER" -p "$DOCKER_HUB_PASSWORD"
            - docker pull myprocessx/deploy-artifact
            - pipe: ozma-io/deploy-artifact:master
      - step:
          name: Deploy to production
          deployment: production
          trigger: manual
          caches:
            - docker
          script:
            - docker login -u "$DOCKER_HUB_USER" -p "$DOCKER_HUB_PASSWORD"
            - docker pull myprocessx/deploy-artifact
            - pipe: ozma-io/deploy-artifact:master
